name: DigArena
main: me.killerkoda13.DigArena.DigArena
version: 0.0.1
description: DigArena generation plugin
author: Killerkoda13
commands:
   generatearena:
      description: generate arena
      usage: /<command>
   additem:
      description: add item to rewards
      usage: /<command>